import { Drug } from './types';

// Mock data for drugs - ~30 items
export const mockDrugs: Drug[] = [
  {
    id: 1,
    therapeuticCategory: "Antibiotic",
    activeIngredient: "Amoxicillin",
    brandName: "Amoxicillin 500mg",
    strength: "500mg",
    dosageForm: "Tablet",
    route: "Oral",
    manufacturer: "PharmaCorp",
    regulationLevel: "Antibiotic",
    imageUrl: "/img/656d7fce-58b5-4b8d-87bb-bf471d9f06f0-md.jpeg"
  },
  {
    id: 2,
    therapeuticCategory: "Analgesic",
    activeIngredient: "Paracetamol",
    brandName: "Tylenol 500mg",
    strength: "500mg",
    dosageForm: "Tablet",
    route: "Oral",
    manufacturer: "Johnson & Johnson",
    regulationLevel: "OTC",
    imageUrl: "/img/744685da-c6dd-454f-a4e3-0925e888f278.jpg"
  },
  {
    id: 3,
    therapeuticCategory: "Antibiotic",
    activeIngredient: "Ciprofloxacin",
    brandName: "Cipro 500mg",
    strength: "500mg",
    dosageForm: "Tablet",
    route: "Oral",
    manufacturer: "Bayer",
    regulationLevel: "Antibiotic",
    imageUrl: "/img/about.jpg"
  },
  {
    id: 4,
    therapeuticCategory: "Antihypertensive",
    activeIngredient: "Amlodipine",
    brandName: "Norvasc 5mg",
    strength: "5mg",
    dosageForm: "Tablet",
    route: "Oral",
    manufacturer: "Pfizer",
    regulationLevel: "Rx",
    imageUrl: "/img/blog-1.jpg"
  },
  {
    id: 5,
    therapeuticCategory: "Antidiabetic",
    activeIngredient: "Metformin",
    brandName: "Glucophage 500mg",
    strength: "500mg",
    dosageForm: "Tablet",
    route: "Oral",
    manufacturer: "Merck",
    regulationLevel: "Rx",
    imageUrl: "/img/blog-2.jpg"
  },
  {
    id: 6,
    therapeuticCategory: "Analgesic",
    activeIngredient: "Ibuprofen",
    brandName: "Advil 400mg",
    strength: "400mg",
    dosageForm: "Tablet",
    route: "Oral",
    manufacturer: "Pfizer",
    regulationLevel: "OTC",
    imageUrl: "/img/blog-3.jpg"
  },
  {
    id: 7,
    therapeuticCategory: "Antibiotic",
    activeIngredient: "Azithromycin",
    brandName: "Zithromax 250mg",
    strength: "250mg",
    dosageForm: "Capsule",
    route: "Oral",
    manufacturer: "Pfizer",
    regulationLevel: "Antibiotic",
    imageUrl: "/img/hero.jpg"
  },
  {
    id: 8,
    therapeuticCategory: "Antihistamine",
    activeIngredient: "Cetirizine",
    brandName: "Zyrtec 10mg",
    strength: "10mg",
    dosageForm: "Tablet",
    route: "Oral",
    manufacturer: "Johnson & Johnson",
    regulationLevel: "OTC",
    imageUrl: "/img/price-1.jpg"
  },
  {
    id: 9,
    therapeuticCategory: "Antacid",
    activeIngredient: "Omeprazole",
    brandName: "Prilosec 20mg",
    strength: "20mg",
    dosageForm: "Capsule",
    route: "Oral",
    manufacturer: "AstraZeneca",
    regulationLevel: "OTC",
    imageUrl: "/img/price-2.jpg"
  },
  {
    id: 10,
    therapeuticCategory: "Antibiotic",
    activeIngredient: "Amoxicillin",
    brandName: "Amoxicillin Suspension 250mg/5ml",
    strength: "250mg/5ml",
    dosageForm: "Suspension",
    route: "Oral",
    manufacturer: "PharmaCorp",
    regulationLevel: "Antibiotic",
    imageUrl: "/img/price-3.jpg"
  },
  {
    id: 11,
    therapeuticCategory: "Analgesic",
    activeIngredient: "Paracetamol",
    brandName: "Paracetamol Injection 1g/100ml",
    strength: "1g/100ml",
    dosageForm: "Injection",
    route: "IV",
    manufacturer: "Generic",
    regulationLevel: "Rx",
    imageUrl: "/img/price-4.jpg"
  },
  {
    id: 12,
    therapeuticCategory: "Bronchodilator",
    activeIngredient: "Salbutamol",
    brandName: "Ventolin Inhaler 100mcg",
    strength: "100mcg",
    dosageForm: "Inhaler",
    route: "Inhalation",
    manufacturer: "GSK",
    regulationLevel: "Rx",
    imageUrl: "/img/team-1.jpg"
  },
  {
    id: 13,
    therapeuticCategory: "Corticosteroid",
    activeIngredient: "Prednisolone",
    brandName: "Prednisolone 5mg",
    strength: "5mg",
    dosageForm: "Tablet",
    route: "Oral",
    manufacturer: "Generic",
    regulationLevel: "Rx",
    imageUrl: "/img/team-2.jpg"
  },
  {
    id: 14,
    therapeuticCategory: "Anticoagulant",
    activeIngredient: "Warfarin",
    brandName: "Coumadin 5mg",
    strength: "5mg",
    dosageForm: "Tablet",
    route: "Oral",
    manufacturer: "Bristol-Myers Squibb",
    regulationLevel: "Rx",
    imageUrl: "/img/team-3.jpg"
  },
  {
    id: 15,
    therapeuticCategory: "Antibiotic",
    activeIngredient: "Cefuroxime",
    brandName: "Zinacef 750mg",
    strength: "750mg",
    dosageForm: "Injection",
    route: "IV/IM",
    manufacturer: "GSK",
    regulationLevel: "Antibiotic",
    imageUrl: "/img/testimonial-1.jpg"
  },
  {
    id: 16,
    therapeuticCategory: "Antifungal",
    activeIngredient: "Fluconazole",
    brandName: "Diflucan 150mg",
    strength: "150mg",
    dosageForm: "Capsule",
    route: "Oral",
    manufacturer: "Pfizer",
    regulationLevel: "Rx",
    imageUrl: "/img/testimonial-2.jpg"
  },
  {
    id: 17,
    therapeuticCategory: "Antiemetic",
    activeIngredient: "Ondansetron",
    brandName: "Zofran 4mg",
    strength: "4mg",
    dosageForm: "Tablet",
    route: "Oral",
    manufacturer: "GSK",
    regulationLevel: "Rx",
    imageUrl: "/img/testimonial-3.jpg"
  },
  {
    id: 18,
    therapeuticCategory: "Antacid",
    activeIngredient: "Ranitidine",
    brandName: "Zantac 150mg",
    strength: "150mg",
    dosageForm: "Tablet",
    route: "Oral",
    manufacturer: "GSK",
    regulationLevel: "OTC",
    imageUrl: "/img/user.jpg"
  },
  {
    id: 19,
    therapeuticCategory: "Antibiotic",
    activeIngredient: "Doxycycline",
    brandName: "Vibramycin 100mg",
    strength: "100mg",
    dosageForm: "Capsule",
    route: "Oral",
    manufacturer: "Pfizer",
    regulationLevel: "Antibiotic",
    imageUrl: "/img/656d7fce-58b5-4b8d-87bb-bf471d9f06f0-md.jpeg"
  },
  {
    id: 20,
    therapeuticCategory: "Analgesic",
    activeIngredient: "Tramadol",
    brandName: "Ultram 50mg",
    strength: "50mg",
    dosageForm: "Capsule",
    route: "Oral",
    manufacturer: "Janssen",
    regulationLevel: "Controlled",
    imageUrl: "/img/744685da-c6dd-454f-a4e3-0925e888f278.jpg"
  },
  {
    id: 21,
    therapeuticCategory: "Antihypertensive",
    activeIngredient: "Losartan",
    brandName: "Cozaar 50mg",
    strength: "50mg",
    dosageForm: "Tablet",
    route: "Oral",
    manufacturer: "Merck",
    regulationLevel: "Rx",
    imageUrl: "/img/about.jpg"
  },
  {
    id: 22,
    therapeuticCategory: "Antidiabetic",
    activeIngredient: "Gliclazide",
    brandName: "Diamicron 80mg",
    strength: "80mg",
    dosageForm: "Tablet",
    route: "Oral",
    manufacturer: "Servier",
    regulationLevel: "Rx",
    imageUrl: "/img/blog-1.jpg"
  },
  {
    id: 23,
    therapeuticCategory: "Antibiotic",
    activeIngredient: "Clarithromycin",
    brandName: "Biaxin 500mg",
    strength: "500mg",
    dosageForm: "Tablet",
    route: "Oral",
    manufacturer: "Abbott",
    regulationLevel: "Antibiotic",
    imageUrl: "/img/blog-2.jpg"
  },
  {
    id: 24,
    therapeuticCategory: "Antihistamine",
    activeIngredient: "Loratadine",
    brandName: "Claritin 10mg",
    strength: "10mg",
    dosageForm: "Tablet",
    route: "Oral",
    manufacturer: "Bayer",
    regulationLevel: "OTC",
    imageUrl: "/img/blog-3.jpg"
  },
  {
    id: 25,
    therapeuticCategory: "Antacid",
    activeIngredient: "Pantoprazole",
    brandName: "Protonix 40mg",
    strength: "40mg",
    dosageForm: "Tablet",
    route: "Oral",
    manufacturer: "Pfizer",
    regulationLevel: "Rx",
    imageUrl: "/img/hero.jpg"
  },
  {
    id: 26,
    therapeuticCategory: "Analgesic",
    activeIngredient: "Diclofenac",
    brandName: "Voltaren 50mg",
    strength: "50mg",
    dosageForm: "Tablet",
    route: "Oral",
    manufacturer: "Novartis",
    regulationLevel: "Rx",
    imageUrl: "/img/price-1.jpg"
  },
  {
    id: 27,
    therapeuticCategory: "Antibiotic",
    activeIngredient: "Levofloxacin",
    brandName: "Levaquin 500mg",
    strength: "500mg",
    dosageForm: "Tablet",
    route: "Oral",
    manufacturer: "Janssen",
    regulationLevel: "Antibiotic",
    imageUrl: "/img/price-2.jpg"
  },
  {
    id: 28,
    therapeuticCategory: "Antihypertensive",
    activeIngredient: "Atenolol",
    brandName: "Tenormin 50mg",
    strength: "50mg",
    dosageForm: "Tablet",
    route: "Oral",
    manufacturer: "AstraZeneca",
    regulationLevel: "Rx",
    imageUrl: "/img/price-3.jpg"
  },
  {
    id: 29,
    therapeuticCategory: "Antifungal",
    activeIngredient: "Clotrimazole",
    brandName: "Canesten Cream 1%",
    strength: "1%",
    dosageForm: "Cream",
    route: "Topical",
    manufacturer: "Bayer",
    regulationLevel: "OTC",
    imageUrl: "/img/price-4.jpg"
  },
  {
    id: 30,
    therapeuticCategory: "Antibiotic",
    activeIngredient: "Ceftriaxone",
    brandName: "Rocephin 1g",
    strength: "1g",
    dosageForm: "Injection",
    route: "IV/IM",
    manufacturer: "Roche",
    regulationLevel: "Antibiotic",
    imageUrl: "/img/team-1.jpg"
  }
];
